import { Location } from '../structure';
import { PaperSlip, BrainTank } from '../items';

const net = new Location('Net Device');
const cpu = new Location('Central Processing Unit');
const carrier = new Location('Carrier');
const scrubber = new Location('Scrubber');
const medical = new Location('Medical Center');
const synth = new Location('Nutrient Synthesizer');
const cargo1 = new Location('Cargo Bay, Fore');
const cargo2 = new Location('Cargo Bay, Aft');
const parts = new Location('Cargo Bay, Lander Parts Storage');
const pad = new Location('Cargo Bay, Lander Pad');
const doors = new Location('Cargo Bay Doors');
const tanks = new Location('Cargo Bay, Resource Tanks');
const station = new Location('Cargo Bay, Bot Station');
const maintainence = new Location('Cargo Bay, Bot Maintainence');
const lock = new Location('Heat Lock Access Point');
const generator = new Location('Generator');
const battery1 = new Location('Battery Section 1');
const battery2 = new Location('Battery Section 2');
const reactor = new Location('Reactor Monitor');
const overUpper = new Location('Over-side Upper Exterior');
const starboardUpper = new Location('Starboard-side Upper Exterior');
const underUpper = new Location('Under-side Upper Exterior');
const portUpper = new Location('Port-side Upper Exterior');
const overLower = new Location('Over-side Lower Exterior');
const starboardLower = new Location('Starboard-side Lower Exterior');
const underLower = new Location('Under-side Lower Exterior');
const portLower = new Location('Port-side Lower Exterior');
const nose = new Location('Nose Exterior');
const tail = new Location('Tail Exterior');

net.link(cpu, 'aft');
cpu.link(carrier, 'aft');
carrier.link(scrubber, 'aft');
medical.link(scrubber, 'starboard');
synth.link(scrubber, 'port');
scrubber.link(cargo1, 'aft');
parts.link(cargo1, 'starboard');
parts.link(pad, 'aft');
tanks.link(cargo1, 'port');
tanks.link(station, 'aft');
cargo1.link(cargo2, 'aft');
pad.link(cargo2, 'starboard');
doors.link(pad, 'starboard');
station.link(cargo2, 'port');
maintainence.link(station, 'port');
cargo2.link(lock, 'aft');
lock.link(generator, 'aft');
battery1.link(generator, 'starboard');
battery2.link(generator, 'port');
generator.link(reactor, 'aft');
portUpper.link(doors, 'aft');
portLower.link(doors, 'fore');
underUpper.link(portUpper, 'starboard');
underLower.link(portLower, 'starboard');
underLower.link(underUpper, 'fore');
starboardUpper.link(underUpper, 'starboard');
starboardLower.link(underLower, 'starboard');
starboardLower.link(starboardUpper, 'fore');
overUpper.link(starboardUpper, 'starboard');
overLower.link(starboardLower, 'starboard');
overLower.link(overUpper, 'fore');
portUpper.link(overUpper, 'starboard');
portLower.link(overLower, 'starboard');
nose.link(overUpper, 'fore', true);
overUpper.link(nose, 'fore', true);
nose.link(underUpper, 'aft', true);
underUpper.link(nose, 'fore', true);
nose.link(portUpper, 'port', true);
portUpper.link(nose, 'fore', true);
nose.link(starboardUpper, 'starboard', true);
starboardUpper.link(nose, 'fore', true);
tail.link(overLower, 'fore', true);
overLower.link(tail, 'aft', true);
tail.link(underLower, 'aft', true);
underLower.link(tail, 'aft', true);
tail.link(portLower, 'port', true);
portLower.link(tail, 'aft', true);
tail.link(starboardLower, 'starboard', true);
starboardLower.link(tail, 'aft', true);

station.description = "In this corner of the cargo bay, there's the frame of a box with open sides. Inside there are various scraps of technology and the damaged carcasses of bots, but all complicated stuff that seems above your pay grade.";

carrier.addContent(new BrainTank());
station.addContent(new PaperSlip());

export default station;